// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7nOOd-Zr6kxYA2n_eL9uIfdLtBS00Jfk',
    appId: '1:831654884350:web:670d9b5218e0f866ec46af',
    messagingSenderId: '831654884350',
    projectId: 'mhdcooperation',
    authDomain: 'mhdcooperation.firebaseapp.com',
    storageBucket: 'mhdcooperation.firebasestorage.app',
    measurementId: 'G-QC0J4E46Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsZg15TsU8qA5CuK9Utm9GRfQiah5Hzo',
    appId: '1:831654884350:android:0398c1b75aa81b8aec46af',
    messagingSenderId: '831654884350',
    projectId: 'mhdcooperation',
    storageBucket: 'mhdcooperation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzdw14nN6iA09vZ_p15bZYKDXQ7AYF6w',
    appId: '1:831654884350:ios:0940d05b928b1d06ec46af',
    messagingSenderId: '831654884350',
    projectId: 'mhdcooperation',
    storageBucket: 'mhdcooperation.firebasestorage.app',
    iosBundleId: 'com.mhdcooperation.com.mhdcooperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFzdw14nN6iA09vZ_p15bZYKDXQ7AYF6w',
    appId: '1:831654884350:ios:0940d05b928b1d06ec46af',
    messagingSenderId: '831654884350',
    projectId: 'mhdcooperation',
    storageBucket: 'mhdcooperation.firebasestorage.app',
    iosBundleId: 'com.mhdcooperation.com.mhdcooperation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7nOOd-Zr6kxYA2n_eL9uIfdLtBS00Jfk',
    appId: '1:831654884350:web:dbe99ed309342688ec46af',
    messagingSenderId: '831654884350',
    projectId: 'mhdcooperation',
    authDomain: 'mhdcooperation.firebaseapp.com',
    storageBucket: 'mhdcooperation.firebasestorage.app',
    measurementId: 'G-99N17X40K5',
  );
}
